// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/403" | "/[locale]/account" | "/[locale]/brands" | "/[locale]/brands/[slug]" | "/[locale]/cart" | "/[locale]/catalog" | "/[locale]/catalog/[slug]" | "/[locale]/checkout" | "/[locale]/checkout/success" | "/[locale]/compare" | "/[locale]/contacts" | "/[locale]/delivery" | "/[locale]/faq" | "/[locale]/guide" | "/[locale]/login" | "/[locale]/maintenance" | "/[locale]/privacy" | "/[locale]/product/[slug]" | "/[locale]/terms" | "/[locale]/wishlist" | "/admin" | "/admin/banners" | "/admin/brands" | "/admin/categories" | "/admin/customers" | "/admin/import" | "/admin/logs" | "/admin/orders" | "/admin/orders/[id]" | "/admin/prices" | "/admin/products" | "/admin/products/[id]" | "/admin/reviews" | "/admin/seo" | "/admin/settings" | "/admin/stock" | "/admin/users"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/register" | "/api/brands" | "/api/cart" | "/api/categories" | "/api/contact" | "/api/cron/feeds" | "/api/feeds/google" | "/api/feeds/sync" | "/api/import" | "/api/np" | "/api/orders" | "/api/orders/[id]" | "/api/products" | "/api/products/[slug]" | "/api/reviews" | "/api/search" | "/api/telegram" | "/api/webhooks"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/403": { "locale": string; }
  "/[locale]/account": { "locale": string; }
  "/[locale]/brands": { "locale": string; }
  "/[locale]/brands/[slug]": { "locale": string; "slug": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/catalog": { "locale": string; }
  "/[locale]/catalog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/checkout": { "locale": string; }
  "/[locale]/checkout/success": { "locale": string; }
  "/[locale]/compare": { "locale": string; }
  "/[locale]/contacts": { "locale": string; }
  "/[locale]/delivery": { "locale": string; }
  "/[locale]/faq": { "locale": string; }
  "/[locale]/guide": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/maintenance": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/product/[slug]": { "locale": string; "slug": string; }
  "/[locale]/terms": { "locale": string; }
  "/[locale]/wishlist": { "locale": string; }
  "/admin": {}
  "/admin/banners": {}
  "/admin/brands": {}
  "/admin/categories": {}
  "/admin/customers": {}
  "/admin/import": {}
  "/admin/logs": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/prices": {}
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/reviews": {}
  "/admin/seo": {}
  "/admin/settings": {}
  "/admin/stock": {}
  "/admin/users": {}
  "/api/auth/login": {}
  "/api/auth/register": {}
  "/api/brands": {}
  "/api/cart": {}
  "/api/categories": {}
  "/api/contact": {}
  "/api/cron/feeds": {}
  "/api/feeds/google": {}
  "/api/feeds/sync": {}
  "/api/import": {}
  "/api/np": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/products": {}
  "/api/products/[slug]": { "slug": string; }
  "/api/reviews": {}
  "/api/search": {}
  "/api/telegram": {}
  "/api/webhooks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
